### ISSUE TITLE
Update to work with rp2040-hal v0.7.0

### ISSUE THREAD

**Issue by riskable** [korken89/rp2040-monotonic#5]
The current version depends on rp2040-hal v0.6.0 explicitly (or something like that) so if you update your code to try to use the new rp2040-hal v0.7.0 it breaks because the types are different.  You get errors like this:

```
538  |         let mut mono = aliases::MonotonicTimer::new(c.device.TIMER);
     |                        ---------------------------- ^^^^^^^^^^^^^^ expected struct `rp2040_pac::TIMER`, found struct `TIMER`
     |                        |
     |                        arguments to this function are incorrect
```

It's because your own code will be trying to use rp2040-hal v0.7.0 while rp2040-monotonic will be using rp2040-hal v0.6.0 (can't mix & match like that).  This is also related to rp2040-pac going from version 0.3 to 0.4 but I'm not sure how that plays into it.

The key issue is that if you try to use the latest version of everything rp2040-monotonic breaks.

**Comment by korken89** [comment]
Hi, you need to run cargo update.
See https://github.com/korken89/rp2040-monotonic/issues/4 for previous discussion, this crate uses the 0.4 PAC directly.

**Comment by riskable** [comment]
Ahh, great:  I was able to work it all out by changing the version in Cargo.toml *then* doing a `cargo update` (silly silly).

**Comment by korken89** [comment]
Glad you got it solved!
